"""Dispatch panels — AI Resolve (Plane issues) + AI Review (open PRs).

AI Resolve restored to a Splide carousel (2026-05-01) reading from the
static `data/issues.json` snapshot generated by the plane-snapshot workflow
every 15 min. The original carousel was removed in PR #12 because Plane
API blocks browser-origin CORS, but PR #14 introduced the same-origin
snapshot which sidesteps that entirely. Cards are colour-coded by `scope`
(front/back/both/other) computed in the snapshot generator — sprint-planning
visual cue so devs can scan and pick.

AI Review stays on the simple manual-input shape — most of the time you
already know the PR number from the link you just opened.
"""

from browser import ajax, document, html, window

from .api import gh_post
from .carousel import SplideCarousel
from .config import PLANE_PROJECT_IDENTIFIER, PLANE_WORKSPACE, REPO
from .start_work import open_modal as open_start_work_modal


# ── Shared ───────────────────────────────────────────────────────

_REPOS = [
    ("frontend-core-2.0", "Visalaw/frontend-core-2.0"),
    ("visalaw-gen-backend", "Visalaw/visalaw-gen-backend"),
    ("visalaw-gen-production-frontend", "Visalaw/visalaw-gen-production-frontend"),
]

_SNAPSHOT_URL = "data/issues.json"


def _on_dispatch(req, status_id):
    status = document[status_id]
    if req.status in (204, 201):
        status.html = '<span class="dispatch-status-ok">&#10003; Dispatched successfully</span>'
    else:
        import json as _json
        try:
            msg = _json.loads(req.text).get("message", f"HTTP {req.status}")
        except Exception:
            msg = f"HTTP {req.status}"
        status.html = f'<span class="dispatch-status-err">Error: {msg}</span>'


def _render_repo_select(select_id, include_all=False):
    sel = html.SELECT(id=select_id, Class="filter-select")
    if include_all:
        sel <= html.OPTION("All repos", value="all")
    for label, value in _REPOS:
        sel <= html.OPTION(label, value=value)
    return sel


def _open_external(ev, url, label):
    """Open URL in new tab with confirmation."""
    ev.stopPropagation()
    ev.preventDefault()
    if window.confirm(f"Open {label}?\n\nThis will open a new tab outside the dashboard."):
        window.open(url, "_blank")


# ═══════════════════════════════════════════════════════════════
#  AI RESOLVE — Plane carousel (snapshot-fed) + manual fallback
# ═══════════════════════════════════════════════════════════════

_resolve_carousel = None


def _render_issue_card(issue):
    """Render a Plane issue as a glass card colour-coded by scope.

    Scope values come from the snapshot generator (`tools/snapshot_plane.py`):
    front | back | both | other. Each maps to a distinct accent in CSS via
    the `scope-<value>` class so the dev can scan-and-pick at a glance,
    sprint-planning style.

    A "Start work" button on the card opens the start_work modal — copy
    buttons for branch, git command, and Cursor/Claude starter prompt.
    """
    scope = (issue.get("scope") or "other").lower()
    card = html.DIV(Class=f"issue-card-body scope-{scope}")

    header = html.DIV(Class="issue-card-header")
    header <= html.SPAN(Class=f"issue-dot scope-dot scope-dot-{scope}")
    header <= html.SPAN(issue["identifier"], Class="issue-id")
    header <= html.SPAN(scope.upper(), Class=f"issue-priority scope-badge-{scope}")
    card <= header

    card <= html.P(issue.get("title", ""), Class="issue-title")

    desc = (issue.get("description") or "").strip()
    if desc:
        card <= html.P(desc, Class="issue-desc")

    meta_row = html.DIV(Class="issue-meta")
    state = issue.get("state", "")
    if state:
        meta_row <= html.SPAN(state)

    # Two work modes per card:
    #   "Copy prompt" → opens local modal with branch + git checkout + Cursor /
    #     Claude starter prompts ready to paste into the dev's editor.
    #     The human does the coding.
    #   "Run VAIR"    → fires ai-resolve.yml on GitHub Actions which spawns
    #     a Claude Code agent that autonomously edits files, runs tests, and
    #     opens a PR. No human in the loop until the PR appears.
    # Labels were "Start work" / "Dispatch" — both opaque about WHO does the
    # work. The new labels name the intent: copy something locally vs run
    # the named product remotely.
    start_btn = html.A("Copy prompt", href="#", Class="issue-start-link",
                       title="Copy branch + git command + Cursor / Claude prompt to your editor (you code the fix)")
    start_btn.bind("click", lambda ev, i=issue: _open_start_work(ev, i))
    meta_row <= start_btn

    dispatch_btn = html.A("Run VAIR", href="#", Class="issue-dispatch-link",
                          title="Trigger the ai-resolve.yml workflow — VAIR agent edits files and opens a PR autonomously")
    dispatch_btn.bind("click", lambda ev, ident=issue["identifier"]:
                      _dispatch_from_card(ev, ident))
    meta_row <= dispatch_btn

    url = issue.get("url", "#")
    link = html.A("↗", Class="issue-link", href="#")
    link.bind("click", lambda ev, u=url, ident=issue["identifier"]:
              _open_external(ev, u, ident))
    meta_row <= link
    card <= meta_row
    return card


def _dispatch_from_card(ev, identifier):
    ev.stopPropagation()
    ev.preventDefault()
    _trigger_resolve(selected=identifier)


def _open_start_work(ev, issue):
    ev.stopPropagation()
    ev.preventDefault()
    open_start_work_modal(issue)


def render_dispatch_resolve():
    """Build the AI Resolve panel — carousel of snapshot top issues + manual fallback."""
    global _resolve_carousel
    panel = document["dispatch-resolve"]
    panel.clear()

    header = html.DIV(Class="runs-header")
    header <= html.H3("AI Resolve")
    actions = html.DIV(Class="runs-header-actions")
    actions <= _render_repo_select("resolve-repo")
    header <= actions
    panel <= header

    panel <= html.DIV(id="resolve-issues", Class="issue-list")

    # Manual input row remains accessible — for issues outside the top 20 or
    # when you already know the identifier and want to skip the carousel.
    # NOTE: no separate Dispatch button here — the carousel injects the
    # primary action; this row prefills the carousel's selected identifier
    # when the user types one. Enter on the input triggers dispatch.
    fallback = html.DIV(Class="dispatch-fallback")
    fallback <= html.SPAN("or", Class="dispatch-fallback-sep")
    fallback <= html.INPUT(
        id="resolve-issue-manual",
        placeholder=f"type {PLANE_PROJECT_IDENTIFIER}-123",
        Class="dispatch-input",
        autocomplete="off",
    )
    panel <= fallback

    panel <= html.DIV(id="resolve-status", Class="dispatch-status")

    # Pressing Enter inside the manual input triggers dispatch with the typed id.
    def _on_manual_keypress(ev):
        if getattr(ev, "key", "") == "Enter":
            _trigger_resolve()
    document["resolve-issue-manual"].bind("keypress", _on_manual_keypress)

    _resolve_carousel = SplideCarousel(
        container_id="resolve-issues",
        carousel_id="resolve-carousel",
        render_card=_render_issue_card,
        get_id=lambda i: i["identifier"],
        on_select=_on_card_select,
        on_action=lambda ident: _trigger_resolve(selected=ident),
        btn_label="Dispatch",
        btn_id="resolve-dispatch-btn-carousel",
        empty_msg="Snapshot not loaded yet. Cron writes data/issues.json every 15 min.",
        per_page=2,
    )
    _load_issues_from_snapshot()


def _on_card_select(identifier):
    """When user picks a card, prefill the manual input so they can edit if needed."""
    try:
        document["resolve-issue-manual"].value = identifier
    except Exception:
        pass


def _load_issues_from_snapshot():
    """Fetch the same-origin Plane snapshot and feed the carousel."""
    if _resolve_carousel:
        _resolve_carousel.loading() if hasattr(_resolve_carousel, "loading") else None
    req = ajax.Ajax()
    req.open("GET", _SNAPSHOT_URL, True)
    req.bind("complete", _on_snapshot_loaded)
    req.send()


def _on_snapshot_loaded(req):
    import json as _json
    if req.status != 200:
        if _resolve_carousel:
            _resolve_carousel.render([])
        return
    try:
        data = _json.loads(req.text)
    except Exception:
        if _resolve_carousel:
            _resolve_carousel.render([])
        return
    items = data.get("top", []) or []
    if _resolve_carousel:
        _resolve_carousel.render(items)


def _trigger_resolve(ev=None, selected=None):
    status = document["resolve-status"]
    repo = document["resolve-repo"].value
    issue = selected or ""
    if not issue and _resolve_carousel:
        issue = _resolve_carousel.selected
    if not issue:
        try:
            issue = document["resolve-issue-manual"].value.strip()
        except Exception:
            issue = ""
    if not issue:
        status.html = '<span style="color:var(--red)">Pick a card or type an issue id (e.g. VISAL-677)</span>'
        return
    status.html = '<span class="spinner"></span> Dispatching...'
    gh_post(f"/repos/{REPO}/actions/workflows/ai-resolve.yml/dispatches",
            {"ref": "main", "inputs": {"repo": repo, "issue": issue}},
            lambda req: _on_dispatch(req, "resolve-status"))


# ═══════════════════════════════════════════════════════════════
#  AI REVIEW — PR review dispatch (manual input only)
# ═══════════════════════════════════════════════════════════════


def render_dispatch_review():
    """Build the AI Review panel: repo + PR number + Run VAIR review.

    Layout mirrors AI Resolve's manual fallback row — input + primary
    action on a single horizontal line — instead of the previous vertical
    stack (LABEL / INPUT / BUTTON). The label was redundant with the
    placeholder; the button label now names the product (VAIR) and the
    user action (run a review) so the intent reads at a glance, same
    convention as 'Run VAIR' on AI Resolve cards.
    """
    panel = document["dispatch-review"]
    panel.clear()

    header = html.DIV(Class="runs-header")
    header <= html.H3("AI Review")
    actions = html.DIV(Class="runs-header-actions")
    actions <= _render_repo_select("review-repo")
    header <= actions
    panel <= header

    body = html.DIV(Class="dispatch-review-row")
    pr_input = html.INPUT(
        id="review-pr-manual",
        placeholder="PR #123",
        Class="dispatch-input",
        autocomplete="off",
        inputmode="numeric",
    )
    pr_input.attrs["type"] = "number"
    pr_input.attrs["min"] = "1"
    body <= pr_input
    btn = html.BUTTON(
        "Run VAIR review",
        Class="dispatch-btn",
        id="review-dispatch-btn",
        title="Posts /ai-review on the PR — VAIR workflow reads the comment and runs a code review",
    )
    btn.attrs["type"] = "button"
    btn.bind("click", _trigger_review)
    body <= btn
    panel <= body
    panel <= html.DIV(id="review-status", Class="dispatch-status")

    # Enter inside the PR input triggers the same dispatch path as the
    # button click. Same pattern as the resolve-issue-manual binding.
    def _on_review_keypress(ev):
        if getattr(ev, "key", "") == "Enter":
            _trigger_review()
    pr_input.bind("keypress", _on_review_keypress)


def _trigger_review(ev=None):
    status = document["review-status"]
    repo = document["review-repo"].value
    try:
        pr_num = document["review-pr-manual"].value.strip()
    except Exception:
        pr_num = ""
    if not pr_num:
        status.html = '<span class="dispatch-status-err">Type a PR number</span>'
        return
    if not pr_num.isdigit():
        status.html = '<span class="dispatch-status-err">PR number must be digits only</span>'
        return
    status.html = '<span class="spinner"></span> Dispatching...'
    gh_post(f"/repos/{repo}/issues/{pr_num}/comments",
            {"body": "/ai-review"},
            lambda req: _on_dispatch(req, "review-status"))
